// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/ValerySidorin/whisper/internal/config"
	"github.com/ValerySidorin/whisper/internal/infrastructure/appctx"
	"github.com/ValerySidorin/whisper/internal/infrastructure/web"
	"github.com/ValerySidorin/whisper/internal/infrastructure/web/routes"
)

// Injectors from wire.go:

func InitWebServer() (*web.Server, error) {
	coreContext := appctx.Register()
	configuration := config.Register()
	router, err := routes.Register(configuration)
	if err != nil {
		return nil, err
	}
	server := web.Register(coreContext, router, configuration)
	return server, nil
}
